version: '3'
services:
  web:
    build:
      context: ..
      dockerfile: docker/images/backend.Dockerfile
    volumes:
      - ..:/app
    ports:
      - "8001:8000"
    env_file:
      - ../.env
    depends_on:
      - db
  db:
    image: postgres:14
    volumes:
      - pg_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: booknooker_by
      POSTGRES_PASSWORD: booknooker_by
      POSTGRES_DB: booknooker_by
    ports:
      - "5433:5432"
volumes:
  pg_data: